import Head from "next/head";
import React, { useCallback, useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import CoverAlbum from "../components/UI/organisms/coveralbum";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import SearchAppBar from "../components/UI/molecules/searchappbar";
import ArtistCharacteristic from "../components/UI/molecules/artistcharacteristic";
import { useSearch } from "../components/UI/context/contextalbum";
import axios from "axios";
import { DataArtist } from "../components/UI/molecules/artistcharacteristic";
import Button from "../components/UI/atoms/button";
import router from "next/router";
import Player from "../components/UI/molecules/player";

//import useAPI from "../src/api/search";

// export type DataArtist = {
//   id: number;
//   title: string;
//   name: string;
// };

// Artist data
// export const getServerSidePropsArtist: GetServerSideProps<{
//   dataArtist: DataArtist;
// }> = async (context) => {
//   const res = await fetch("https://api.deezer.com/artist/27");
//   const dataArtist: DataArtist = await res.json();

//   return {
//     props: {
//       dataArtist,
//     },
//   };
// };

const Home = () => {
  const { state, dispatch } = useSearch();
  const [dataResult, setdataResult] = useState<any>([]);

  function showDetailsArtist() {
    router.push("/artist/" + state.search);
  }

  const useAPI = async (search: string) => {
    try {
      const response = await axios.get(
        `http://api.deezer.com/search?q=${search}`
      );
      setdataResult(response?.data);
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    useAPI(state.search);
  }, [state.search]);

  return (
    <div>
      <Head>
        <title>Create Next App - Deezer Exo</title>
        <meta
          name='Mon app Deezer'
          content='Generated by create next app'
        />
      </Head>
      <main>
        <SearchAppBar />
        <div className={styles.container}>
          <h1>Retrouve ta musique préférée</h1>
          <button onClick={showDetailsArtist}>Découvrir + sur l'artiste</button>
          {/* <Button name={{ search }}></Button> */}
          <div className={styles.containerv2}>
            {dataResult?.data ? (
              <>
                {dataResult.data?.map((DataArtist: DataArtist) => (
                  <div
                    className={styles.albumContainer}
                    key={DataArtist.id}
                  >
                    <div className={styles.containerv3}>
                      <ArtistCharacteristic
                        ArtistCharacteristicData={{ DataArtist }}
                      />

                      <CoverAlbum CoverAlbumData={{ DataArtist }} />
                      <Player track={{ DataArtist }}></Player>
                    </div>
                  </div>
                ))}
              </>
            ) : (
              <div>Taper un artiste</div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
