import Head from "next/head";
import React from "react";
// import styles from "../styles/Home.module.css";
import CoverAlbum from "../components/UI/organisms/coveralbum";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import SearchAppBar from "../components/UI/molecules/searchappbar";

type Data = {};
type DataArtist = {};

export const getServerSideProps: GetServerSideProps<{ data: Data }> = async (
  context
) => {
  const res = await fetch("https://api.deezer.com/artist/27");
  const data: Data = await res.json();

  return {
    props: {
      data,
    },
  };
};

export const getServerSidePropsArtist: GetServerSideProps<{
  data: DataArtist;
}> = async (context) => {
  const res = await fetch("https://api.deezer.com/artist/27");
  const data: DataArtist = await res.json();

  return {
    props: {
      data,
    },
  };
};

const Home = ({
  data,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <div>
      {/* <div className={styles.container}></div> */}
      <Head>
        <title>Create Next App - Deezer Exo</title>
        <meta
          name='Mon app Deezer'
          content='Generated by create next app'
        />
      </Head>
      {/* <main className={styles.main}> */}
      <main>
        {/* <SearchAppBar /> */}
        <h1>Retrouve ta musique préférée</h1>
        <CoverAlbum />
        <>{console.log("data - STEP 01", data)}</>
      </main>
    </div>
  );
};

export default Home;
