import Head from "next/head";
import React, { useCallback, useEffect, useState } from "react";
import styles from "../../styles/Home.module.css";
import CoverAlbum from "../../components/UI/organisms/coveralbum";
import {
  GetServerSideProps,
  GetServerSidePropsContext,
  InferGetServerSidePropsType,
} from "next";
import SearchAppBar from "../../components/UI/molecules/searchappbar";
import ArtistCharacteristic from "../../components/UI/molecules/artistcharacteristic";
import { useSearch } from "../../components/UI/context/contextalbum";
import axios from "axios";
import DataArtist from "../../components/UI/molecules/artistcharacteristic";
import Button from "../../components/UI/atoms/button";
import router from "next/router";
import Player from "../../components/UI/molecules/player";

const Home = () => {
  const { dataResult, setdataResult, state, dispatch } = useSearch();
  const search = state.search;
  const [selectedItems, setSelectedItems] = useState<any>([]);
  const [DataArtist, setItems] = useState([dataResult]);
  const [isLoading, setIsLoading] = useState(true);
  const [playlist, setPlaylist] = useState([]);
  const [stateHeart, setHeart] = useState(false);

  const handleAddToPlaylist = (track?: any) => {
    setHeart(!stateHeart);
    // dispatch({ type: "update_playlist", payload: data });
    const newPlaylist = [...playlist, track];
    setPlaylist(newPlaylist);
    localStorage.setItem("playlist", JSON.stringify(newPlaylist));
    console.log("newPlaylist");
  };

  // const handleItemClick = (DataArtist: any) => {
  //   setSelectedItems([...selectedItems, DataArtist.name]);
  //   console.log("hello");
  // };

  function showDetailsArtist() {
    router.push("/artist/" + search);
  }

  // ici je fais pas getServerSideProps car setdataResult. tu es coté client tu veux updater tes datas
  const useAPI = async (search: string) => {
    const { data: result } = await axios.get(`/api/search?q=${search}`);
    result && setdataResult(result?.data);
  };

  useEffect(() => {
    useAPI(search);
    setIsLoading(false);
  }, [search]);

  useEffect(() => {
    const savedPlaylist = localStorage.getItem("playlist");
    if (savedPlaylist) {
      setPlaylist(JSON.parse(savedPlaylist));
    }
    console.log("savedPlaylist", savedPlaylist);
  }, [state.stateHeart]);

  //
  if (isLoading) {
    return <div>Loading...</div>;
  } else {
    return (
      <div>
        <Head>
          <title>Create Next App - Deezer Exo</title>
          <meta
            name='Mon app Deezer'
            content='Generated by create next app'
          />
        </Head>
        <main>
          <SearchAppBar />
          <div className={styles.container}>
            <h1>Retrouve ta musique préférée</h1>
            <button onClick={showDetailsArtist}>
              Découvrir + sur l'artiste
            </button>
            {/* <Button name={{ search }}></Button> */}
            <div className={styles.containerv2}>
              {dataResult ? (
                <>
                  {dataResult?.map((DataArtist: any) => (
                    <div
                      className={styles.albumContainer}
                      key={DataArtist.id}
                    >
                      <div className={styles.containerv3}>
                        <ArtistCharacteristic
                          ArtistCharacteristicData={{ DataArtist }}
                        />
                        {state.stateHeart ? (
                          <CoverAlbum
                            onClick={() => state.addMusic(dataResult)}
                            CoverAlbumData={{ DataArtist }}
                          />
                        ) : (
                          <CoverAlbum CoverAlbumData={{ DataArtist }} />
                        )}
                        <Player track={{ DataArtist }}></Player>
                      </div>
                    </div>
                  ))}
                </>
              ) : (
                <div>Taper un artiste</div>
              )}
            </div>
          </div>
        </main>
      </div>
    );
  }
};

export default Home;
